name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: bun-linux-x64
            output: varset-linux-x64
          - os: macos-latest
            target: bun-darwin-arm64
            output: varset-macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun build ./index.ts --compile --target=${{ matrix.target }} --outfile ${{ matrix.output }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: |
          mkdir -p release-artifacts
          mv varset-linux-x64/varset-linux-x64 release-artifacts/
          mv varset-macos-arm64/varset-macos-arm64 release-artifacts/
          ls -la release-artifacts/
      - uses: softprops/action-gh-release@v1
        with:
          files: release-artifacts/*
          generate_release_notes: true
